FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Build the React app
ARG REACT_APP_API_URL
ENV REACT_APP_API_URL=$REACT_APP_API_URL
RUN npm run build


# Serve with static server
RUN npm install -g serve
CMD ["serve", "-s", "build", "-l", "3000"]
