version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
    networks:
      - tetrominos-net

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: http://localhost:5001
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - tetrominos-net


networks:
  tetrominos-net:
